#!/usr/bin/env bash
# Run tests on a newly created Vagrant box.
set -o errexit

vagrant destroy --force
vagrant up
vagrant ssh --command 'cd /vagrant && rake && sudo rake install && maid version --long && maid help && maid sample'
