#!/usr/bin/env bash
# Run this script on a precise32 VM created with Vagrant to test installation, etc.
#
# It depends on the `.deb` being present in the `pkg` directory. 
#
# Usage:
#
#     host$ script/vagrant-test # calls this file
set -o errexit

apt-get -qq update
apt-get -qq install -y gdebi
# NOTE: Using a glob is easier than being specific, be wary if something goes wawry:
gdebi --non-interactive --quiet pkg/maid*.deb

# FIXME: doesn't work because of `mdls`
# mkdir -p "$HOME/Downloads"
# touch "$HOME/Downloads/ubuntu.iso"
# touch "$HOME/Downloads/chrome.deb"

script/smoke-test

apt-get -qq remove -y maid
