#!/usr/bin/env bash
# Run this script on a precise32 VM created with Vagrant to test installation, etc.
#
# It depends on the `.deb` being present in the `pkg` directory. 
#
# Usage:
#
#     host$ script/vagrant-test # calls this file
set -o errexit

function echo_cmd {
  echo \$ $*
  $*
}

apt-get -qq update
apt-get -qq install -y gdebi
# NOTE: Using a glob is easier than being specific, be wary if something goes wawry:
gdebi --non-interactive --quiet pkg/maid*.deb

# FIXME: doesn't work because of `mdls`
# mkdir -p "$HOME/Downloads"
# touch "$HOME/Downloads/ubuntu.iso"
# touch "$HOME/Downloads/chrome.deb"

echo '-----------------------------------------------------------------------'
echo '  Smoke test starting...'
echo '-----------------------------------------------------------------------'

echo_cmd maid version
echo_cmd maid --help
echo_cmd maid help
echo_cmd maid
echo_cmd maid sample
echo_cmd mv -v ~/.maid/rules.sample.rb ~/.maid/rules.rb
echo_cmd maid help clean
echo_cmd maid clean --dry-run

echo '-----------------------------------------------------------------------'
echo '  Smoke test finished'
echo '-----------------------------------------------------------------------'

apt-get -qq remove -y maid
