#!/usr/bin/env bash
# A simple shell-based provisioner for Vagrant.
# 
# Documentation: [Shell Provisioner](http://vagrantup.com/v1/docs/provisioners/shell.html)
set -o errexit

target_ruby_version="$1"

# Install the given package, no questions asked.
function install-pkg {
  sudo apt-get install -y "$1"
}

# Only install the given package if targeting the given Ruby version.
function install-pkg-if-ruby {
  local ruby_version="$1"
  local package="$2"

  if [ "$target_ruby_version" == "$ruby_version" ]; then
    install-pkg "$package"
  fi
}

function install-ruby {
  sudo apt-get install -y build-essential tar bzip2 xz-utils hashalot grep wget patch
  wget https://github.com/postmodern/ruby-install/releases/download/v0.9.0/ruby-install-0.9.0.tar.gz
  tar -xzvf ruby-install-0.9.0.tar.gz
  cd ruby-install-0.9.0/
  sudo make install
  ruby-install --system ruby "$target_ruby_version"
}

function enable-rspec {
  echo 'export ISOLATED=true' >> /home/vagrant/.profile
}

sudo apt-get update

# ## Dependencies
# Installs `ruby 1.9.3p0`
install-pkg-if-ruby '1.9.3' 'ruby1.9.1'
install-pkg-if-ruby 'jruby' 'jruby'
# Install specified Ruby
install-ruby

# ## Development dependencies
#
# For building `maid-x.y.z.gem`
install-pkg 'git-core'
# For building `ffi` for `guard`'s soft dependency on `rb-inotify`
install-pkg 'make'
install-pkg 'libffi-dev'
install-pkg-if-ruby '1.9.3' 'ruby1.9.1-dev'

enable-rspec
sudo gem install bundler
cd /vagrant
bundle install
