#!/usr/bin/env bash
# A simple shell-based provisioner for Vagrant.
# 
# Documentation: [Shell Provisioner](http://vagrantup.com/v1/docs/provisioners/shell.html)
set -o errexit

# Set to '1.9.3', 'jruby'
target_ruby_version="${1:-1.9.3}"

# Install the given package, no questions asked.
function install-pkg {
  sudo apt-get install -y "$1"
}

# Only install the given package if targeting the given Ruby version.
function install-pkg-if-ruby {
  local ruby_version="$1"
  local package="$2"

  if [ "$target_ruby_version" == "$ruby_version" ]; then
    install-pkg "$package"
  fi
}

sudo apt-get update

# ## Dependencies
# Installs `ruby 1.9.3p0`
install-pkg-if-ruby '1.9.3' 'ruby1.9.1'
install-pkg-if-ruby 'jruby' 'jruby'

# ## Development dependencies
#
# For building `maid-x.y.z.gem`
install-pkg 'git-core'
# For building `ffi` for `guard`'s soft dependency on `rb-inotify`
install-pkg 'make'
install-pkg 'libffi-dev'
install-pkg-if-ruby '1.9.3' 'ruby1.9.1-dev'

sudo gem install bundler
cd /vagrant
bundle install
