#!/usr/bin/env bash
# Test all officially supported Ubuntu versions.
#
# See also: `Vagrantfile`

MAID_TARGET_BOX='hardy32'   MAID_TARGET_RUBY='1.8.7' script/vagrant-test
# TODO: Locate and add box for `hardy64`
MAID_TARGET_BOX='lucid32'   MAID_TARGET_RUBY='1.8.7' script/vagrant-test
MAID_TARGET_BOX='lucid64'   MAID_TARGET_RUBY='1.8.7' script/vagrant-test
# TODO: Locate and add box for `oneiric32`
MAID_TARGET_BOX='oneiric64' MAID_TARGET_RUBY='1.8.7' script/vagrant-test
MAID_TARGET_BOX='precise32' MAID_TARGET_RUBY='1.9.3' script/vagrant-test
MAID_TARGET_BOX='precise64' MAID_TARGET_RUBY='1.9.3' script/vagrant-test
# TODO: Locate and add box for `quantal32`
MAID_TARGET_BOX='quantal64' MAID_TARGET_RUBY='1.9.3' script/vagrant-test
