#!/usr/bin/env bash
# Test all officially supported Ubuntu versions.
#
# See also: `Vagrantfile`

# ## Base Boxes
#
# To add a [box](http://vagrantup.com/v1/docs/boxes.html):
#
#     vagrant box add $box_name $box_url
#
# Base boxes for supported releases are listed below.  The idea is to come close to the [official Canonical support timeline](http://en.wikipedia.org/wiki/Ubuntu_releases#Table_of_versions), when possible.
#
# ### Releases preferred with Ruby 1.9.3
#
# Supported until 2017-04:
#
# * `precise32`: http://files.vagrantup.com/precise32.box
# * `precise64`: http://files.vagrantup.com/precise64.box
#
# Supported until 2014-07:
#
# * `saucy32`
# * `saucy64`
#
# ## See Also
# 
# * [Vagrant Boxes List](http://www.vagrantbox.es/)
# * [Contributing Guide](https://github.com/benjaminoakes/maid/wiki/Contributing)

MAID_TARGET_BOX='precise32' MAID_TARGET_RUBY='1.9.3' script/vagrant-test
MAID_TARGET_BOX='precise64' MAID_TARGET_RUBY='1.9.3' script/vagrant-test
# TODO: Locate and add box for `saucy32`
# TODO: Locate and add box for `saucy64`
