name: Upload coverage to Code Climate

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: bundle exec rake
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}
          COVERAGE: true
          ISOLATED: true
