permissions:
  contents: read
name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install commitlint
        run: npm install -g @commitlint/config-conventional @commitlint/cli
      - name: Validate current commit (push)
        if: github.event_name == 'push'
        run: echo "${{ github.event.head_commit.message }}" | commitlint
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version derived from .ruby-version file
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run lint
        run: bundle exec rubocop
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Shellcheck
        run: sudo apt install shellcheck -y
      - name: Run shellcheck
        run: shellcheck -x script/*

  pr-title-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
