name: Release

on:
  push:
    branches:
      - master
  # FIXME: Don't ship this
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head.ref }}
      - name: Prepare release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Don't use GITHUB_TOKEN because this doesn't allow workflows to
          # trigger workflows; it leave the `release-please`-generated PR with
          # pending checks as they're never started.
          token: ${{ secrets.BOT_GH_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
        # FIXME: Don't ship this
        env:
          ACTIONS_STEP_DEBUG: "true"
          DRY_RUN: "true"
      # FIXME: Don't ship this commented out
      #
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     # ruby-version derived from .ruby-version file
      #     bundler-cache: true
      #   if: ${{ steps.release.outputs.release_created }}
      # - name: Install dependencies
      #   run: bundle install
      #   if: ${{ steps.release.outputs.release_created }}
      # - name: Run tests
      #   run: bundle exec rake
      #   env:
      #     ISOLATED: true
      #   if: ${{ steps.release.outputs.release_created }}
      # - name: Publish gem
      #   run: |
      #     mkdir -p $HOME/.gem
      #     touch $HOME/.gem/credentials
      #     chmod 0600 $HOME/.gem/credentials
      #     printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
      #     gem build *.gemspec
      #     gem push *.gem
      #   env:
      #     GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
      #   if: ${{ steps.release.outputs.release_created }}
