name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    needs: [commitlint, test, rubocop, shellcheck]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version derived from .ruby-version file
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec
          bundle install

      - name: Run tests
        run: bundle exec rake
        env:
          ISOLATED: true

      - name: Configure gem credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ::add-mask::${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
        run: |
          npx semantic-release
